settings:
  title: 'ZeAyの状态'
  url: 'https://hz64.github.io' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统运行正常'
  notAllmonitorsOperational: '并非所有系统都能正常运行'
  monitorLabelOperational: '正常运行'
  monitorLabelNotOperational: '未运行'
  monitorLabelNoData: '没有数据'
  dayInHistogramNoData: '没有数据'
  dayInHistogramOperational: '全部正常'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: hz64.github.io # unique identifier
    name: hz64.github.io - 个人主页
    description: '现在全部交给hz6.us.kg域名' # default=empty
    url: 'https://hz64.github.io/' # URL to fetch
    method: GET # default=GET
    expectStatus: 301 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: hz6.us.kg
    name: hz6.us.kg - 全部服务
    description: '全部服务在这里'
    url: 'https://hz6.us.kg/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog.hz6.us.kg
    name: blog.hz6.us.kg - 博客
    url: 'https://blog.hz6.us.kg/'
    method: GET
    expectStatus: 200

  - id: xcxc.us.kg
    name: xcxc.us.kg - xcxc
    url: 'https://xcxc.us.kg/'
    method: GET
    expectStatus: 200
